/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SoilAnalysisResult = IDL.Record({
  'recommendedCrops' : IDL.Vec(IDL.Text),
  'preventionTips' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StoreItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Float64,
});
export const PaymentMethod = IDL.Record({
  'cvv' : IDL.Text,
  'expiryDate' : IDL.Text,
  'cardHolderName' : IDL.Text,
  'cardNumber' : IDL.Text,
});
export const Order = IDL.Record({
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'confirmationNumber' : IDL.Text,
  'items' : IDL.Vec(StoreItem),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'location' : IDL.Text,
});
export const CropListing = IDL.Record({
  'id' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'quantity' : IDL.Float64,
  'cropName' : IDL.Text,
  'location' : IDL.Text,
  'farmer' : IDL.Principal,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'price' : IDL.Float64,
  'location' : IDL.Text,
});
export const CropAdvisoryParams = IDL.Record({
  'region' : IDL.Text,
  'pHLevel' : IDL.Float64,
  'soilType' : IDL.Text,
  'moisture' : IDL.Float64,
});
export const CropRecommendation = IDL.Record({
  'riskReductionTips' : IDL.Vec(IDL.Text),
  'crops' : IDL.Vec(IDL.Text),
  'sustainablePractices' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCropListing' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addStoreItem' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat], [IDL.Text], []),
  'analyzeSoilImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [SoilAnalysisResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func(
      [IDL.Vec(StoreItem), IDL.Float64, PaymentMethod],
      [Order],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCropListingsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CropListing)],
      ['query'],
    ),
  'getOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getProductsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getSmartCropAdvisory' : IDL.Func(
      [CropAdvisoryParams],
      [CropRecommendation],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SoilAnalysisResult = IDL.Record({
    'recommendedCrops' : IDL.Vec(IDL.Text),
    'preventionTips' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StoreItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const PaymentMethod = IDL.Record({
    'cvv' : IDL.Text,
    'expiryDate' : IDL.Text,
    'cardHolderName' : IDL.Text,
    'cardNumber' : IDL.Text,
  });
  const Order = IDL.Record({
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'confirmationNumber' : IDL.Text,
    'items' : IDL.Vec(StoreItem),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'location' : IDL.Text,
  });
  const CropListing = IDL.Record({
    'id' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'quantity' : IDL.Float64,
    'cropName' : IDL.Text,
    'location' : IDL.Text,
    'farmer' : IDL.Principal,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'price' : IDL.Float64,
    'location' : IDL.Text,
  });
  const CropAdvisoryParams = IDL.Record({
    'region' : IDL.Text,
    'pHLevel' : IDL.Float64,
    'soilType' : IDL.Text,
    'moisture' : IDL.Float64,
  });
  const CropRecommendation = IDL.Record({
    'riskReductionTips' : IDL.Vec(IDL.Text),
    'crops' : IDL.Vec(IDL.Text),
    'sustainablePractices' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCropListing' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addStoreItem' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat], [IDL.Text], []),
    'analyzeSoilImage' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [SoilAnalysisResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func(
        [IDL.Vec(StoreItem), IDL.Float64, PaymentMethod],
        [Order],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCropListingsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CropListing)],
        ['query'],
      ),
    'getOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getProductsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSmartCropAdvisory' : IDL.Func(
        [CropAdvisoryParams],
        [CropRecommendation],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };