/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CropAdvisoryParams {
  'region' : string,
  'pHLevel' : number,
  'soilType' : string,
  'moisture' : number,
}
export interface CropListing {
  'id' : string,
  'pricePerUnit' : number,
  'quantity' : number,
  'cropName' : string,
  'location' : string,
  'farmer' : Principal,
}
export interface CropRecommendation {
  'riskReductionTips' : Array<string>,
  'crops' : Array<string>,
  'sustainablePractices' : Array<string>,
}
export interface Order {
  'status' : string,
  'total' : number,
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'confirmationNumber' : string,
  'items' : Array<StoreItem>,
}
export interface PaymentMethod {
  'cvv' : string,
  'expiryDate' : string,
  'cardHolderName' : string,
  'cardNumber' : string,
}
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'seller' : Principal,
  'price' : number,
  'location' : string,
}
export interface SoilAnalysisResult {
  'recommendedCrops' : Array<string>,
  'preventionTips' : Array<string>,
}
export interface StoreItem {
  'id' : string,
  'name' : string,
  'stock' : bigint,
  'price' : number,
}
export interface UserProfile { 'username' : string, 'location' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCropListing' : ActorMethod<[string, number, number, string], string>,
  'addProduct' : ActorMethod<[string, string, number, string], string>,
  'addStoreItem' : ActorMethod<[string, number, bigint], string>,
  'analyzeSoilImage' : ActorMethod<[Uint8Array], SoilAnalysisResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[Array<StoreItem>, number, PaymentMethod], Order>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCropListingsByLocation' : ActorMethod<[string], Array<CropListing>>,
  'getOrders' : ActorMethod<[Principal], Array<Order>>,
  'getProductsByLocation' : ActorMethod<[string], Array<Product>>,
  'getSmartCropAdvisory' : ActorMethod<
    [CropAdvisoryParams],
    CropRecommendation
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];